# Generated by Django 5.2 on 2025-07-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_title_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
